wheniwork/wheniwork-api

source/methods/times.md.erb

The start and end parameters have been removed because the endpoint ignores them anyway! Also added user_id parameter to the "Listing Times" section.

Update /times/user to remove start and end dates

---

source/methods/payrolls.md.erb
source/methods/times.md.erb

Some sections of the docs seemed to indicate that you needed to enter start and end dates in the format YYYY-MM-DD. This was misleading, since those endpoints do in fact accept dates in a more specific format.
At some point, maybe we could put in a section near the top explaining what date formats will be accepted throughout the API.

Remove YYYY-MM-DD from docs

---

config.rb
lib/common.rb
source/index.md.erb
source/methods/payrolls.md.erb
source/methods/plans.md.erb
source/methods/times.md.erb
source/stylesheets/screen.css.scss

More complicated than I wanted it to be, but it works, and we can keep RedCarpet as our Markdown parser.

Enable Markdown parsing in asides

---

config.rb
lib/api_html_renderer.rb
source/javascripts/all.js
source/stylesheets/screen.css.scss

Sections of JSON code can now be hidden until they are expanded by the user. To do this, just enclose the code to hide between two new lines, one with SECTION_START and one with SECTION_END. As long as those words are somewhere on those lines, it'll work.
For example, `email` and `phone_number` would both be hidden until the user expands them:
```json
{
"id": 4364,
"first_name": "Goldie",
"last_name": "Wilson",
SECTION_START
"email": "goldiewilson@hillvalleycalifornia.gov",
"phone_number": "555-555-5555"
SECTION_END
}
```
To accomplish this feature I had to create a new Markdown renderer. Eventually we may even extend this to do other things, but for now it just handles this specific feature.

Enable collapsible sections of JSON

---

lib/api_html_renderer.rb
source/javascripts/all.js
source/stylesheets/screen.css.scss

Tables can now be collapsed, much like blocks of code. Surrounding rows with SECTION_START and SECTION_END will collapse those rows by default. Then clicking a link that appears below the table will expand those rows to allow you to see everything.
Here's an example of what the syntax might look like:
```
Key | Description
--- | -----------
start | <strong>datetime</strong><br />Start time for a search window
end | <strong>datetime</strong><br />End time for a search window
user_id | <strong>integer, string array</strong><br />Only show shifts for a user, or multiple (e.g. 1,5,3)
location_id | <strong>integer, string array</strong><br />Only show shifts for a location, or multiple.
site_id | <strong>integer, string array</strong><br />Only show shifts for a site, or multiple.
position_id …
```

Add ability to collapse tables

---

data/objects.json
source/methods/shifts.md.erb

Documentation for shifts has been improved overall. All parameters now have a type annotation, all shell and PHP examples use the same data, and text has been clarified wherever possible.
One specific point of confusion this resolves is how the `start` and `end` parameters work on the Listing Shifts endpoint. The examples now use both date and time, instead of just date. There have been several support tickets stemming from confusion over that point.

Improve docs for shifts

---

lib/common.rb

Having a single common method for parameters in a table will let us manage the formatting of those parameters in a saner way later on. As it is, if we ever want to change how the type of a parameter is
displayed, we have to change it tediously across the entire docs.
We will have to do that once for this change but then we would never have to do that again.
**Before:**
```erb
end | End time for the search window. The default is exactly three days from the start time.
```
**After:**
```erb
<% param "end" do %>End time for the search window. The default is exactly three days from the start time.<% end %>
```
**Before:**
```erb
start | <strong>datetime</strong><br />Start time for the search window. The default is the current date and time.
```
**After:**
```erb
<% param "start", "datetime" …
```

Add common "param" method for query parameters

---

lib/api_objects.rb
lib/common.rb

The parameters outputted by print_table were still outputting raw Markdown instead of being formatted using the `param` method. Now there is a `make_param` method that returns a string, and the `param` method uses this to build the parameter to output.

Make print_table use param method

---

lib/api_objects.rb
source/index.md.erb
source/methods/accounts.md.erb
source/methods/annotations.md.erb
source/methods/availabilities.md.erb
source/methods/blocks.md.erb
source/methods/devices.md.erb
source/methods/locations.md.erb
source/methods/messages.md.erb
source/methods/payrolls.md.erb
source/methods/plans.md.erb
source/methods/positions.md.erb
source/methods/requests.md.erb
source/methods/send.md.erb
source/methods/shifts.md.erb
source/methods/sites.md.erb
source/methods/swaps.md.erb
source/methods/templates.md.erb
source/methods/times.md.erb
source/methods/users.md.erb

When using the `print_json` method, we almost never wanted to actually print out *all* the fields of an object, so we were using the `:minimal` option almost every time. Now `:minimal` has been replaced with `:verbose`, its opposite. That way we have a sensible default, and we can only show all fields when we really want to. 
In the near future this may be expanded or revised to allow for those extra fields to be displayed, but collapsed by default.
Also tidies up `api_objects.rb`.

Switch JSON :minimal to :verbose

---

source/methods/users.md.erb

Endpoints for getting and updating user profiles are presently described as targeting "a user," which is ambiguous and implies they can target any user when in fact they are specific to the authenticated user. This change modifies the endpoint descriptions to provide clarification on this point.

Clarify description of user profile endpoints

---

source/methods/availabilities.md.erb

This endpoint does not include `availability` in the output.

Update availability items documentation

---

source/methods/shifts.md.erb

The `include_open` and `include_allopen` parameters are slightly different.
cc @CherryPepsi

Fix incomplete documentation for open shift inclusion

---

source/methods/batch.md.erb

Batching is terrible for performance and regularly causes server
timeouts due to large transfer sizes.

Add deprecation notice for batch method

---

source/methods/accounts.md.erb

This change came from conversation on this issue:
[WEB-3054](https://wheniwork.atlassian.net/browse/WEB-3054)
- Removing the Account Listing section
- Describing the case in which an account listing is included in the GET Account section

Clarify Account Listing WEB-3054

---

lib/api_objects.rb

Using objects as field values with print_json resulted in unparsed output from objects.json:
```json
"place": {
"business_name": {
"show": true,
"type": "string",
"description": "(Optional) Business Name",
"value": "When I Work"
},
"address": {
"show": true,
"type": "string",
"description": "Place Address",
"value": "60 Plato Blvd, St Paul, MN 55107, United States"
}
}
```
With this update, these objects are recursively handled:
```json
"place": {
"business_name": "When I Work",
"address": "60 Plato Blvd, St Paul, MN 55107, United States"
}
```

Recursively handle hash values in JSON

---

source/methods/requests.md.erb
source/methods/swaps.md.erb

Listing requests and swaps includes output that includes the total
number of results, the current page, and if more pages are available.
Refs WEB-3306
Refs wheniwork/wheniwork-app#3864

Add missing documentation for requests/swaps

---

data/objects.json
source/methods/shifts.md.erb

Refs https://github.com/wheniwork/wheniwork-api/issues/98
I know we aren't actually using the shift history attributes object but the documentation is at least there now.

Documents the shift history endpoint

---

source/methods/schedule.md.erb

👋 Hi there! First time caller. Thank you so much for providing your documentation in an open source repository so that fixes like this can occur 🙏.
This pull request resolves an error in the documentation for the `position_id` argument of the ["Fetching Schedules"](http://dev.wheniwork.com/#fetching-schedule) endpoint when multiple _position_ IDs are passed as an argument.

Fix error in schedule endpoint for querying multiple positions

---

data/objects.json
source/index.md.erb
source/methods/forecasting.md.erb

Main question: Is this a thing we want in the docs? I see no reason not to include it.

Add documentation for projected sales endpoint

---

README.md

The homepage URL wasn't an SSL link, but going to the non-SSL redirects
there anyway.
The link to the documentation was a 404.

Fix URL to When I Work homepage (add SSL) and doc page
