wheniwork/wheniwork-api

source/methods/shifts.md.erb
See wheniwork/wheniwork-app#546 and wheniwork/wheniwork-app@27056896eead7a0edef2599ced930828640e7403
=> Add documentation for shift acknowledgement

source/index.md.erb
Removed references to kittens and teapots, as well as corrected some
spelling error.
=> Re-worded Error section

data/objects.json, lib/api_objects.rb, source/methods/users.md.erb
Also:
* Added a new method called `print_json_as_php_array` which can be used to print out data declared in `objects.json` in PHP format (it's unfortunately not nicely formatted though).
=> Add documentation for profile updating.

source/index.md.erb
:book:
cc @ceramicatheist @jwir3
=> Add documentation for include_objects

lib/common.rb, source/index.md.erb, source/methods/accounts.md.erb, source/methods/annotations.md.erb, source/methods/availabilities.md.erb, source/methods/batch.md.erb, source/methods/blocks.md.erb, source/methods/locations.md.erb, source/methods/messages.md.erb, source/methods/payrolls.md.erb, source/methods/plans.md.erb, source/methods/positions.md.erb, source/methods/requests.md.erb, source/methods/send.md.erb, source/methods/shifts.md.erb, source/methods/sites.md.erb, source/methods/swaps.md.erb, source/methods/templates.md.erb, source/methods/times.md.erb, source/methods/users.md.erb
All JSON in the API docs is now handled through the json function in common.rb. We are no longer allowed to have invalid JSON in our docs!
This is a huge PR, but the only part that really needs review is common.rb.
=> Standardize JSON output

data/objects.json, source/index.md.erb, source/methods/devices.md.erb
I added these endpoints to the Android core library and noticed we needed API docs.
=> Add documentation for Device POST and DELETE.

data/objects.json, source/methods/devices.md.erb
Refs https://github.com/wheniwork/apitests/pull/7
=> Update Device endpoint docs

source/index.md.erb
Fixes https://github.com/wheniwork/wheniwork-app/issues/2481
=> Adding login/register endpoint documentation

source/methods/swaps.md.erb
Refs wheniwork/wheniwork-app#2552
=> Add documentation of swaps options

data/objects.json, source/methods/accounts.md.erb, source/methods/locations.md.erb
@shadowhand @mvanhorne 
Descriptions could probably use some better wording. please suggest.
Ref: WEB-2929 WEB-2815
=> Add place objects to endpoints

data/objects.json
Refs https://github.com/wheniwork/wheniwork-app/pull/2969
=> Update coordinates objects to include correct return types

data/objects.json, source/methods/accounts.md.erb
Refs wheniwork/wheniwork-app#2964
=> Add features to account documentation

source/index.md.erb
=> Add password requirements for registration

data/objects.json, source/index.md.erb, source/methods/industries.md.erb
=> Add documentation for industry endpoint

source/methods/industries.md.erb
=> Add documentation for industry place endpoint

source/methods/industries.md.erb
=> Correct output example for industry matching

data/objects.json
=> Add bad_credit_card to accounts documentation WEB-3162

source/methods/requests.md.erb
=> Add include_deleted_users param to requests docs WEB-3150

data/objects.json, source/index.md.erb
=> Add docs for login/find endpoint

source/index.md.erb
=> Add more details about account find parameters

source/methods/users.md.erb
=> Add documentation for user avatar update

data/objects.json
=> Add employee-control to features documentation WEB-3167

source/index.md.erb
=> Remove reference to login email in user object

data/objects.json
Refs wheniwork/wheniwork-app#2964
=> Add unclaimed feature to list

source/methods/times.md.erb
Refs https://github.com/wheniwork/wheniwork-app/pull/3140
=> Add location to times

source/methods/accounts.md.erb
Adding account claim endpoint documentation
=> Add account claim endpoint documentation

source/methods/accounts.md.erb
=> Add docs for account invite endpoint

lib/api_objects.rb, source/index.md.erb
Lots of content revisions and changes in this one, so I figured I would get this one properly reviewed.
This was a big overhaul, so I recommend downloading it to view it.
=> Clean up/revise Authentication section

data/objects.json
=> Add note about shift published date null value WEB-3878

source/methods/accounts.md.erb, source/methods/locations.md.erb
Probably shouldnt be merged until workplaces is activated for everyone though.
=> Add place objects to account and location examples

source/methods/shifts.md.erb
Should not be merged before the same branch name on wheniwork-app is merged
=> Add doc for updated shift/acknowledge endpoint

source/methods/shifts.md.erb
=> Add warning about 90 day limit for shift listing

source/index.md.erb, source/methods/login.md.erb, source/methods/users.md.erb
Refs: https://github.com/wheniwork/wheniwork-app/pull/2975
=> Add documentation for avatar creation/upload endpoints

data/objects.json
Refs wheniwork/wheniwork-app#2605
=> Document punches.application_id column

data/objects.json
=> Add API docmentation changes related to workchat

data/objects.json
Documentation updates for wheniwork/wheniwork-app#3642
Refs WEB-4322
=> Add login_id to user response documentation

source/methods/users.md.erb
Refs wheniwork/wheniwork-app#3562
=> Add documentation for multi-user invite

source/index.md.erb, source/methods/schedule.md.erb
=> Add documentation for schedule endpoint

data/objects.json, source/methods/schedule.md.erb
=> Add documentation for the schedule images endpoint

source/methods/annotations.md.erb
=> Document the new HEAD call for annotations

source/methods/shifts.md.erb
Refs WEB-4816
Here's the corresponding app PR: https://github.com/wheniwork/wheniwork-app/pull/3920
=> Document the GET shifts/count endpoint

source/methods/shifts.md.erb
=> documenting deleted query param for shift list

source/methods/accounts.md.erb
=> Fix docs for GET /account

source/methods/accounts.md.erb
This is only partially complete but it covers the data the mobile devs need for now w/o making things too ugly.
Refs ACORE-553
=> Documenting /account/settings endpoint (partially)

data/objects.json, source/methods/accounts.md.erb
=> Add Account holder info to account docs WEB-4950

source/methods/accounts.md.erb
https://wheniwork.atlassian.net/browse/GROW-639
=> Document referral_reason in account creation.

data/objects.json
user_status is similar to status with the addition of a Denied status.
allowed_statuses is a list of valid state transitions (user status
values) for the request based on the current user's rights.
=> TR-11 Added new fields to the public API documentation

data/objects.json
Apparently we also accept hours for partial day requests.
=> Fixed description for hours property of Requests

source/methods/accounts.md.erb
Account (manager) invite now has email and phone number combined into one field.
=> Updating docs for WEB-4681
